# Generated by Django 5.2.6 on 2025-09-26 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0003_alter_klass_assistants'),
        ('teacher_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=4, max_digits=10)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.schoolyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_management.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'school_year'), name='uix_basesalary_teacher_school_year')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('salary', models.DecimalField(decimal_places=6, max_digits=18)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_management.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'month'), name='uix_monthlypayment_teacher_month')],
            },
        ),
    ]
