# Generated by Django 5.2.6 on 2025-10-02 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'منشی'), (2, 'Educationmanager'), (3, 'Educationemployee'), (4, 'Financialmanager'), (5, 'Financialemployee'), (6, 'مربی')]),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
