# Generated by Django 5.2.6 on 2025-09-26 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('phone', models.TextField(max_length=20)),
                ('manager_name', models.TextField(max_length=250)),
                ('robotic_manager_name', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tp', models.PositiveSmallIntegerField(choices=[(1, 'ترم 1'), (2, 'ترم 2'), (3, 'ترم تابستانی')])),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.schoolyear')),
            ],
        ),
    ]
