# Generated by Django 5.2.6 on 2025-09-26 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('teacher_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('time', models.SmallIntegerField(choices=[(60, 'Min60'), (90, 'Min90'), (120, 'Min120')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.semester')),
            ],
        ),
        migrations.CreateModel(
            name='KlassAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.klass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_management.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='klass',
            name='assistants',
            field=models.ManyToManyField(null=True, related_name='klasses_as_assistant', through='education.KlassAssistant', through_fields=('klass', 'teacher'), to='teacher_management.teacher'),
        ),
        migrations.CreateModel(
            name='KlassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.klass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_management.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='klass',
            name='teachers',
            field=models.ManyToManyField(related_name='klasses', through='education.KlassTeacher', through_fields=('klass', 'teacher'), to='teacher_management.teacher'),
        ),
    ]
