# Generated by Django 5.2.6 on 2025-09-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_klass_klassassistant_klass_assistants_klassteacher_and_more'),
        ('teacher_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='assistants',
            field=models.ManyToManyField(related_name='klasses_as_assistant', through='education.KlassAssistant', through_fields=('klass', 'teacher'), to='teacher_management.teacher'),
        ),
    ]
