# Generated by Django 5.2.6 on 2025-09-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_klass_end_time_klass_start_time'),
        ('teacher_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report', models.TextField()),
                ('students', models.JSONField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Submitted'), (2, 'Accepted'), (3, 'Unaccepted')], default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.klass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher_management.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'klass', 'date'), name='uix_sessionreport_teacher_klass_date'), models.UniqueConstraint(fields=('klass', 'date'), name='uix_sessionreport_klass_date')],
            },
        ),
    ]
